apiVersion: v2
name: alfred
description: A Helm chart for Alfred Agent Platform v2
type: application
version: v0.9.3-pre
appVersion: "v0.9.3-pre"
dependencies:
  - name: prometheus
    version: "~15.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "~7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: diagnostics-bot
    version: "0.1.0"
    condition: diagnostics.enabled
  - name: explainer-bot
    version: "0.1.0"
    condition: explainer.enabled
